# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: technicald
# "service" is the name of this project. This will also be added to your AWS resource names.
service: email-api

provider:
  name: aws
  runtime: python3.12

functions:
  sendEmail:
    handler: handler.send_email_api
    timeout: 30
    events:
      - httpApi:
          path: /send-email
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000